# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ogólnopolska Konferencja Naukowa - Oblicza przebaczenia
email: oblicza.przebaczenia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Katolicki Uniwersytet Lubelski im. Jana Pawła II
  Al. Racławickie 14 <br>
  20-950 Lublin
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
